# Generated by Django 3.1.7 on 2021-03-14 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deportes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='descripcion',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='nombre',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='tipo',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='comentarios',
            name='comentario',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='comentarios',
            name='fecha',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='comentarios',
            name='usuario',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='deportes',
            name='articulo',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='deportes',
            name='deporte',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='deportes',
            name='fecha',
            field=models.TextField(default='', null=True),
        ),
    ]
