# Generated by Django 3.1.7 on 2021-03-14 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deportes', '0002_auto_20210314_1656'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deportes',
            old_name='fecha',
            new_name='imagen',
        ),
    ]
