# Generated by Django 3.1.7 on 2021-03-17 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deportes', '0004_auto_20210315_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='imagen',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='deportes',
            name='imagen',
            field=models.TextField(default='', null=True),
        ),
    ]
