# Generated by Django 3.1.7 on 2021-03-17 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deportes', '0005_auto_20210316_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='imagen',
            field=models.ImageField(default='', upload_to='albums/images/'),
        ),
        migrations.AlterField(
            model_name='deportes',
            name='imagen',
            field=models.ImageField(default='', upload_to='albums/images/'),
        ),
    ]
